# Make sure to check the documentation at http://goreleaser.com
project_name: lw-cli
before:
  hooks:
    - go mod verify
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  ldflags: -X github.com/liquidweb/liquidweb-cli/version.Version={{ .Env.VERSION }}  -X github.com/liquidweb/liquidweb-cli/version.BuildTime={{ .Env.BUILDTIME }}  -X github.com/liquidweb/liquidweb-cli/version.GitCommit={{ .Env.GITCOMMIT }}
# archives:
# - replacements:
#     darwin: Darwin
#     linux: Linux
#     windows: Windows
#     amd64: x86_64
# checksum:
#   name_template: 'checksums.txt'
# snapshot:
#   name_template: "{{ .Tag }}"
# changelog:
#   sort: asc
#   filters:
#     exclude:
#     - '^docs:'
#     - '^test:'
nfpms:
  - 
    # replacements:
    #   amd64: x86_64
    vendor: "Liquid Web LLC"
    license: "Apache 2"
    homepage: "https://liquidweb.com"
    description: "LiquidWeb command line client"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - rpm
      - deb
    bindir: "/usr/local/bin"
